language: python
python:
  #  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python git python-dev g++ sox make  curl cmake
    - sudo apt-get install -qq cmake libinsighttoolkit3-dev libpng12-dev libgdcm2-dev
    - sudo apt-get install -qq libfreetype6 libfreetype6-dev libasound2 libasound2-dev alsa-base alsa-utils python python-dev python-setuptools libxinerama-dev libxrender-dev libxcomposite-dev libxcursor-dev swig libglu1-mesa-dev libfreeimage3 libglew1.10 libpng12-0 libpng12-dev libjpeg-dev libxxf86vm1 libxxf86vm-dev libxi6 libxi-dev libxrandr-dev mesa-common-dev mesa-utils-extra libgl1-mesa-dev libglapi-mesa
    # python packages
    # - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-sklearn python-dicom python-yaml 
    # - sudo apt-get install -qq python-qt4 python-vtk python-setuptools python-pip cython
    # python-skimage
    # - wget http://147.228.240.61/queetech/sample-extra-data/io3d_sample_data.zip && unzip io3d_sample_data.zip
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    #  Update conda else if will result in a problem when conda updates the repos...
    - conda update --yes conda
    # GUI
    - "export DISPLAY=:99.0"
    - sh -e /etc/init.d/xvfb start
# command to install dependencies
install:
    - conda update --yes conda 
    # Install dependencies
    - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib scikit-learn scikit-image cython pyqt pyyaml setuptools pip vtk
    - pip install -r ci/requirements_ci.txt
    # - if [ ${pack} == "old_mpl" ]; then conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose dateutil pandas statsmodels pil six; fi
    # - if [ ${pack} == "newest" ]; then conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose dateutil pandas statsmodels six; fi
    # scikit-image
    # - "pip install pyyaml"
    - "easy_install SimpleITK PyOpenGL PyOpenGL-accelerate"
    # my packages
    # install skelet3d
    - "pip install pysegbase sed3 io3d"
    - "git clone https://github.com/cvdlab/lar-cc.git"
    - "git clone https://github.com/plasm-language/pyplasm"
    - cd pyplasm
    - mkdir build
    - cd build
    - cmake ..
    - sudo make install
    - cd ..https://github.com/plasm-language/pyplasm
    # - git clone https://github.com/mjirik/skelet3d.git
    # - mkdir skelet3d/build
    # - cd skelet3d/build
    # - cmake ..
    # - make
    # - sudo make install
    # - cd ..
    # - cd ..
    # gco_python
    # - "git clone https://github.com/mjirik/gco_python.git"
    # - "cd gco_python"
    # - make
    # - "pip install ."
    # - cd ..
    # # ubuntu installer is not working
    # # - 'sudo ./ubuntu_installer.sh devel'
    # - 'echo "include /usr/local/lib" | sudo tee -a /etc/ld.so.conf'
    # - 'sudo ldconfig -v'
    # - python mysetup.py -d
    
# command to run tests
script: nosetests --with-coverage --cover-package=lisa
after_success:
    - coveralls
